site_name: OpenTraceLab
site_description: Open-source logic analysis — capture, view, and decode traces.
site_url: https://opentracelab.github.io/website/
repo_name: OpenTraceLab/website
repo_url: https://github.com/OpenTraceLab/website
edit_uri: edit/main/docs/
use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - content.action.edit       # "Edit this page" button
    - content.action.view       # "View source" button
    - toc.follow                # TOC follows scroll
    - content.code.copy
  icon:
    edit: material/pencil
    view: material/eye
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: indigo
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: indigo  
  #palette:
  #  - scheme: slate
  #    primary: indigo
  #    accent: indigo
  #logo: assets/logo/opentracelab_logo_transparent_tight.svg
  logo: assets/logo/opentracelab_icon_square.svg
  favicon: assets/logo/opentracelab_icon_square.svg

nav:
  - Home: index.md
  - Get started:
      - Install: get-started/install.md
      - Capture your first trace: get-started/capture-first-trace.md
      - FAQ: get-started/faq.md
  - OpenTraceCapture:
      - Overview: opentracecapture/overview.md
      - Driver API: opentracecapture/driver-api.md
      - C API: api/opentracecapture-c/index.md
      - C++ API: api/opentracecapture-cxx/index.md
  - OpenTraceView:
      - Overview: opentraceview/overview.md
      - Architecture: opentraceview/architecture.md
      - API: ../api/opentraceview/index.html
  - OpenTraceDecode:
      - Overview: opentracedecode/overview.md
      - Decoder HOWTO: opentracedecode/decoder-howto.md
      - Decoder API: opentracedecode/decoder-api.md
      - API: ../api/opentracedecode/index.html
  - OpenTraceBroadcaster:
      - Overview: opentracebroadcaster/overview.md
  - Hardware:
      - Supported Devices: hardware/supported-hardware.md
  - Community:
      - Contributing: community/contributing.md
      - Code of Conduct: community/code-of-conduct.md
      - Governance: community/governance.md
      - Testing: community/testing.md
  - About:
      - Mission: about/mission.md
      - Roadmap: about/roadmap.md
  - Legal:
      - License: legal/license.md
      - Attribution: legal/attribution.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search
  - macros
  - glightbox:
      auto_caption: true       # automatically create captions for images
      touch_navigation: true   # enable touch navigation for images
      loop: false               # loop images in galleries

extra_javascript:
  - js/hw-filter.js

validation:
  nav:
    omitted_files: ignore
    not_found: warn
  links:
    not_found: ignore

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OpenTraceLab

extra_javascript:
  - overrides/assets/javascripts/report-issue.js
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

extra_css:
  - overrides/assets/styles/extra.css
  - stylesheets/logo-size.css
  - stylesheets/infobox.css
  - stylesheets/gallery.css
  - stylesheets/hw-table.css
