site_name: OpenTraceLab
site_description: Open-source logic analysis — capture, view, and decode traces.
site_url: https://opentracelab.github.io/website/   # updated by mike per version
repo_name: OpenTraceLab/website
repo_url: https://github.com/OpenTraceLab/website
edit_uri: edit/main/docs/
use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - content.action.edit       # "Edit this page" button
    - content.action.view       # "View source" button
    - toc.integrate
    - content.code.copy
  icon:
    edit: material/pencil
    view: material/eye
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  logo: logo.png
  favicon: docs-assets/logos/favicon.png

nav:
  - Home: index.md
  - Get started:
      - Install: get-started/install.md
      - Capture your first trace: get-started/capture-first-trace.md
      - FAQ: get-started/faq.md
  - OpenTraceCapture:
      - Overview: opentracecapture/overview.md
  - OpenTraceView:
      - Overview: opentraceview/overview.md
      - Architecture: opentraceview/architecture.md
  - OpenTraceDecode:
      - Overview: opentracedecode/overview.md
      - Decoder HOWTO: opentracedecode/decoder-howto.md
      - Decoder API: opentracedecode/decoder-api.md
  - OpenTraceBroadcaster:
      - Overview: opentracebroadcaster/overview.md
  - Hardware:
      - Supported Devices: hardware/supported-hardware.md
      - Logic Analyzers:
          - FX2-based Devices: hardware/logic-analyzer/fx2lafw.md
          - Saleae Logic Series: hardware/logic-analyzer/saleae-logic.md
          - Saleae Logic16: hardware/logic-analyzer/saleae-logic16.md
          - Kingst LA Series: hardware/logic-analyzer/kingst-la-series.md
          - Kingst LA2016: hardware/logic-analyzer/kingst-la2016.md
          - Hantek 4032L: hardware/logic-analyzer/hantek-4032l.md
          - OpenBench LogicSniffer: hardware/logic-analyzer/openbench-logic-sniffer.md
      - Multimeters:
          - UNI-T Series: hardware/multimeter/uni-t.md
          - UNI-T UT61E: hardware/multimeter/uni-t-ut61e.md
          - Voltcraft Series: hardware/multimeter/voltcraft.md
          - Voltcraft VC-820: hardware/multimeter/voltcraft-vc-820.md
          - Brymen Series: hardware/multimeter/brymen.md
      - Oscilloscopes:
          - Rigol DS Series: hardware/oscilloscope/rigol-ds.md
          - Rigol DS1000Z Series: hardware/oscilloscope/rigol-ds1000z-series.md
          - Hantek DSO Series: hardware/oscilloscope/hantek-dso.md
          - Siglent SDS Series: hardware/oscilloscope/siglent-sds.md
      - Power Supplies:
          - Korad Series: hardware/power-supply/korad.md
          - Korad KA3005P: hardware/power-supply/korad-ka3005p.md
          - Rigol DP Series: hardware/power-supply/rigol-dp.md
      - Function Generators:
          - Rigol DG Series: hardware/function-generator/rigol-dg1000z-series.md
          - Siglent SDG Series: hardware/function-generator/siglent-sdg1010.md
      - Thermometers:
          - Voltcraft DL Series: hardware/thermometer/voltcraft-dl-161s.md
          - RDing TEMPer Series: hardware/thermometer/rding-temper.md
  - Community:
      - Contributing: community/contributing.md
      - Code of Conduct: community/code-of-conduct.md
      - Governance: community/governance.md
      - Testing: community/testing.md
  - About:
      - Mission: about/mission.md
      - Roadmap: about/roadmap.md
  - Legal:
      - License: legal/license.md
      - Attribution: legal/attribution.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search
  - mike:
      alias_type: copy         # nice default, keeps old versions intact
      version_selector: true   # show selector in header if theme supports it

extra:
  version:
    provider: mike             # tell Material to use mike's versions
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OpenTraceLab

extra_javascript:
  - overrides/assets/javascripts/report-issue.js
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

extra_css:
  - overrides/assets/styles/extra.css
