name: Deploy Documentation

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: false
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        
    - name: Deploy versioned docs
      run: |
        export GIT_LFS_SKIP_SMUDGE=1
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          mike deploy --config-file mkdocs-versioned.yml $VERSION latest --update-aliases --push
        else
          mike deploy --config-file mkdocs-versioned.yml dev --push
        fi
        
    - name: Deploy hardware docs
      run: |
        export GIT_LFS_SKIP_SMUDGE=1
        mkdocs build --config-file mkdocs-hardware.yml --site-dir site-hardware
        git checkout gh-pages
        mkdir -p hardware
        cp -r site-hardware/* hardware/
        git add hardware/
        git commit -m "Update hardware documentation" || echo "No changes to hardware docs"
        git push origin gh-pages
        git checkout main
        
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: false
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Test build versioned
      run: |
        mkdocs build --config-file mkdocs-versioned.yml --strict
        
    - name: Test build hardware
      run: |
        mkdocs build --config-file mkdocs-hardware.yml --strict
